---
# scrape interval in seconds
scrape-interval: 60

# list of IP addresses of all servers to
server-ips:
  - "127.0.0.1:5050"
  - "10.0.2.9:5050"

# influxdb bucket info
server-bucket-name: "servers"
container-bucket-name: "containers"

...